### ISSUE TITLE
Computing resources usage

### ISSUE THREAD

**Issue by daydayup247** [October2001/ProLong#3]
How many GPUs are required to train the model using the next token prediction objective through prolong? Thank you.

**Comment by October2001** [comment]
Thank you for your interest in ProLong!

**Comment by October2001** [comment]
Thank you for your interest in ProLong!
ProLong is merely a tool for selecting high-quality long-context data. The number of GPUs required for training depends on several factors including your model size, context window size, and parallelization strategy, among others.
